version: "3.7"
services:
  nginx:
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    command: php-fpm
